### ISSUE TITLE
Since phpBB 3.1.6

### ISSUE THREAD

**Issue by Galixte** [bb3mobi/imgposts#14]
Hi @bb3mobi,

it seems it doesn’t work since phpBB 3.1.6, take a look here: https://www.phpbb.com/community/viewtopic.php?p=14242501#p14242501.

**Comment by ouiouiphoto** [comment]
Hello @bb3mobi i have find the problem. It is in the helper.php. A query is too long because this call a table not used

line 485 there is 

$sql = 'SELECT a.attach_id, a.post_msg_id, a.extension, p.post_id, p.topic_id, p.post_time, p.post_visibility
         FROM ' . ATTACHMENTS_TABLE . ' a, ' . POSTS_TABLE . ' p, ' . TOPICS_TABLE . ' t
         WHERE a.post_msg_id = p.post_id
         AND (mimetype = "image/jpeg" OR mimetype = "image/png" OR mimetype = "image/gif")
         AND p.post_visibility = 1
         GROUP BY a.post_msg_id DESC LIMIT ' . $this->config['last_images_attachment_count'] .' ';

and the TOPICS_TABLE is not usefull. So you can change it by 

$sql = 'SELECT a.attach_id, a.post_msg_id, a.extension, p.post_id, p.topic_id, p.post_time, p.post_visibility
         FROM ' . ATTACHMENTS_TABLE . ' a, ' . POSTS_TABLE . ' p
         WHERE a.post_msg_id = p.post_id
         AND (mimetype = "image/jpeg" OR mimetype = "image/png" OR mimetype = "image/gif")
         AND p.post_visibility = 1
         GROUP BY a.post_msg_id DESC LIMIT ' . $this->config['last_images_attachment_count'] .' ';

Unfortunately your extension has been put as ABD by phpBB extension team

**Comment by bb3mobi** [comment]
Ok.
